export const environment = {
  production: false,
  appId:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGU4NzFhYTY4NWVjNDAwMTQ1MGI5NWQiLCJpYXQiOjE2OTI5NTUwNTAsImV4cCI6MTY5NDE2NDY1MH0.l16PZh6oEWnaf6KolxTQGIkHhKPZOgN9OlYg-BQQFKY",
};
