export const environment = {
  private:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGUzMTczZjFmMTc1YzAwMTRjNTU4ZDMiLCJpYXQiOjE2OTI2MDQyMjQsImV4cCI6MTY5MzgxMzgyNH0.gB-qIWHXPJVAXvfEWelfBO8_YihhVILfoygBwkn6qHo"

};
